### ISSUE TITLE
appveyor issue (possible related to declaring the script as a code block)

### ISSUE THREAD

**Issue by guillermooo** [randy3k/UnitTesting#19]
I've had quite a hard time getting tests to run in the FSharp package. Here's more info:

https://github.com/fsharp/fsharpbinding/pull/847#issuecomment-64949539

This is consistent with the fact that all my other packages are able to run the tests just fine, and they are all using `ps:` style commands in the appveyor.yml file.

**Comment by guillermooo** [comment]
Closing this. Was probably my fault.

**Comment by randy3k** [comment]
Thanks.
