### ISSUE TITLE
alternative test result display

### ISSUE THREAD

**Issue by andyli** [randy3k/UnitTesting#23]
Is it possible to redirect the test result to a file or something, instead of using the message panel?

The problem is, I want to run a command in a test, which will display thing on the message panel, thus hiding the test result from me...

**Comment by guillermooo** [comment]
:+1: 

It'd be great to be able to `tail` the output.

**Comment by randy3k** [comment]
It should not be too hard to do it. I can do it in two ways, either
1) specify the filename in `unittesting.json`
2) prompt to ask
3) of course, both

**Comment by guillermooo** [comment]
I vote (1) or (3).

**Comment by andyli** [comment]
Yes, using `unittesting.json` sounds good to me. So, I vote (1) or (3) too :)

**Comment by randy3k** [comment]
Done. Check out v.0.5.2 and see [here](https://github.com/randy3k/UnitTesting-example#redirect-test-result-to-a-file) for the documentation.

**Comment by andyli** [comment]
Thanks!
One problem: Seems like the `output` value only accepts absolute path. It would be great if a path relative to the project folder can be accepted too.

**Comment by randy3k** [comment]
Done. :)

**Comment by andyli** [comment]
Works perfectly! Thanks!
