### ISSUE TITLE
testing agains multiple builds of ST

### ISSUE THREAD

**Issue by guillermooo** [randy3k/UnitTesting#25]
I think this is possible now by modifying the existing scripts, but perhaps it's worth including such functionality by default? I could take a look at it, but some guidance would be appreciated.

**Comment by randy3k** [comment]
Do you mean testing different versions of sublime text? Says, ST2 and ST3?

**Comment by guillermooo** [comment]
Nope. ST3 build 100 and 101; and ST2 build 100, 101 and 102, for example.

**Comment by randy3k** [comment]
I think it should be quite possible on linux server, but it could be slight difficult on mac and window machines. Particularly, `brew cask` of [mac](https://github.com/randy3k/UnitTesting/blob/b8be10f643cdc29d44a75d5d0679ddae10ea993e/sbin/travis.sh#L12) does not allow simple version control and the [ah hoc approach](https://github.com/randy3k/UnitTesting/blob/b8be10f643cdc29d44a75d5d0679ddae10ea993e/sbin/appveyor.ps1#L8) of `appveyor` is also hard to be extended.

**Comment by randy3k** [comment]
I also discovered that `ppa:webupd8team/sublime-text-3` does not keep the old versions.
```
vagrant@precise64:~$ apt-cache madison sublime-text-installer
sublime-text-installer | 3083-1~webupd8~0 | http://ppa.launchpad.net/webupd8team/sublime-text-3/ubuntu/ precise/main amd64 Packages
sublime-text-installer | 3083-1~webupd8~0 | http://ppa.launchpad.net/webupd8team/sublime-text-3/ubuntu/ precise/main Sources
```

**Comment by guillermooo** [comment]
Closing for now. It's been a long time.
