### ISSUE TITLE
add text-based spec format for command tests

### ISSUE THREAD

**Issue by guillermooo** [randy3k/UnitTesting#27]
In Vintageous, I'm using a plain text format to declare tests for ST commands. This allows me to write the tests much faster than in Python code.

Long-term, I'd like to 'outsource' all the testing to a specialized package like UnitTesting. Given that the text-based approach is generally useful, what do you think about including a similar feature in UT?

Here's an example file:

https://github.com/guillermooo/Vintageous/blob/master/tests/commands/vi_x-internal-normal-mode.cmd-test

My current implementation is very simple, but it could be extended with the following features:
- check state of view/window settings
- better traceback fo failing .cmd-test
- teleport user to failing .cmd-test
- options to toggle checking of selections before/after and possibly other options
- autogeneration of .cmd-test stubs for all *Command classes found in the project
- ...

**Comment by randy3k** [comment]
Um, it would be also nice to have some helper functions.

**Comment by guillermooo** [comment]
Closing for now. It's been a long time.
