### ISSUE TITLE
differentiate between $PACKAGE (name) and $PACKAGE_PATH (location)

### ISSUE THREAD

**Issue by guillermooo** [randy3k/UnitTesting#29]
In the [F# package](https://github.com/fsharp/sublime-fsharp-package), the actual ST package is a nested dir. I don't think UnitTesting can handle this case conveniently.

Perhaps in the config vars we should have a `$PACKAGE` (package's name) and a `$PACKAGE_PATH` (relative to the cloned repo). It would default to the current dir as currently.

**Comment by randy3k** [comment]
Agree.

**Comment by guillermooo** [comment]
I think this is already available?

**Comment by randy3k** [comment]
I don’t think so. However, it seems that package control only unpacks files at the top directory. It may make sense to restrict it.
