### ISSUE TITLE
Run syntax_test* tests

### ISSUE THREAD

**Issue by FichteFoll** [randy3k/UnitTesting#32]
See http://www.sublimetext.com/forum/viewtopic.php?f=2&t=18634&p=69227#p69227 for brainstorming.

Ideally, it would work like this in `.travis.yml`:

```yaml
script:
    - sh travis.sh run_tests  # comment this if not needed
    - sh travis.sh run_syntax_tests  # comment this if not needed
```

Dependant on #31, until this is released on beta channel.

**Comment by randy3k** [comment]
It would be much easier to wait the next public beta...

**Comment by randy3k** [comment]
It is basically done. Just need to do more testings. Check this [repo](https://github.com/randy3k/UnitTesting-example/tree/syntax) for a skim.

Travis CI: https://travis-ci.org/randy3k/UnitTesting-example/builds/109998821
Apperv: https://ci.appveyor.com/project/randy3k/unittesting-example/build/1.0.61
