### ISSUE TITLE
Change pattern of unittest discover

### ISSUE THREAD

**Issue by AbdealiJK** [randy3k/UnitTesting#34]
Is there any method to set a different pattern for test files ?

I prefer <name>Test rather than test_<name> and was hoping I could change it.

**Comment by randy3k** [comment]
Unittesting default loader searches for `test*.py. There is no easy way to set a different pattern now.

**Comment by randy3k** [comment]
In the new version (0.5.5), you can provide the pattern for discover in unittesting.json
