### ISSUE TITLE
Use the last used package name for the "Quick Run"

### ISSUE THREAD

**Issue by pradyunsg** [randy3k/UnitTesting#35]
Instead of looking for a package with the same name as the Package, it might be better idea to run the tests for the package for which the tests were last run in the project.

**Comment by pradyunsg** [comment]
Or add another command to run tests for the last selected package

**Comment by randy3k** [comment]
If you hit "UnitTesting" instead of "Quick Run", the default package should be the most recent package. And I argue that pressing the Enter key once should not bother you too much..

**Comment by randy3k** [comment]
no longer relevant.
