### ISSUE TITLE
Output saved to file if unittesting.json is missing

### ISSUE THREAD

**Issue by dim-an** [randy3k/UnitTesting#39]
If plugin doesn't have unittesting.json output is redirected to file, otherwise if unittesting.json is present (even without any meaningful settings) output is shown on panel.

This took me some time to understand why I don't see test results. I think we should output test results to panel by default even if unittesting.json is missing.

**Comment by randy3k** [comment]
Oh...it is a bug, it used to output to the panel...

**Comment by dim-an** [comment]
Thanks  a lot!

**Comment by randy3k** [comment]
I will release an update once the travis and appveyor tests are passed.
