### ISSUE TITLE
load only default preferences

### ISSUE THREAD

**Issue by niosus** [randy3k/UnitTesting#40]
Thanks for a great plugin! It is extremely useful for Sublime Text plugin development! :+1: 

My question is: do you think it is possible to make tests load only default settings, so NOT the user settings? It seems to make sense as then we can test against initial state of the plugin. I gave it a thought, but this seems to be internal to sublime. Any ideas? Do you think it might be useful?

**Comment by randy3k** [comment]
I think it could done by moving the User preference file to somewhere else and then move it back when the tests are done.

However, this may not be something useful, at least for two reasons

1. the travis/appveyor CI tests are tested against the default settings
2. allowing users to test plugins using their own settings is one of the reasons of doing unittest.

A more useful feature may be to repeat the tests using different User preference files.

**Comment by niosus** [comment]
ah, moving the user prefs is nice idea, didn't think of it! Also, I somehow missed the fact that the external tests on travis/appveyor are indeed doing just what I have asked. However, I do agree that it would be nice to be able to test against multiple user preferences. 

My usecase is already covered then, feel free to close or change the issue as you like. And thanks for a fast response!

**Comment by randy3k** [comment]
I will close this for now. You are welcome to submit any feature requests. Cheers.
