### ISSUE TITLE
"update_check": false doesn't work on Sublime Text 3

### ISSUE THREAD

**Issue by randy3k** [randy3k/UnitTesting#43]
it may lead to errors on travis and appveyou CI if the installed sublime text is not the latest.

**Comment by randy3k** [comment]
The installation scripts have been updated to download Sublime Text 3 directly from sublimetext.com.

https://github.com/randy3k/sublime_text_installer/commit/063e8cb7de84e46667836e57f9b1d3ac16ceaecb

It will make sure that the latest version of Sublime Text 3 will be installed.

**Comment by buildersbrewery** [comment]
@randy3k

`"update_check"` is only available to registered users. I guess you can close this as "wontfix" although it isn't relevant anymore due to your workaround.

**Comment by randy3k** [comment]
You are right.
