### ISSUE TITLE
Appveyor stopped working

### ISSUE THREAD

**Issue by niosus** [randy3k/UnitTesting#47]
It seems that guys at Appveyor have changed something. I tried running a recent build for your example project and it fails with the following output:
```
Build started
git clone -q --branch=master https://github.com/niosus/UnitTesting-example.git C:\projects\unittesting-example
git checkout -qf bb61670216685cdcb5ebb6cc5312b0cb3c72ee6c
Running Install scripts
start-filedownload "https://raw.githubusercontent.com/randy3k/UnitTesting/master/sbin/appveyor.ps1"
Downloading appveyor.ps1 (2,094 bytes)...100%
```

Then it hangs and eventually fails the build after the timeout. Any ideas on why that may be the case?

**Comment by randy3k** [comment]
I re-ran my appveyor [tests](https://ci.appveyor.com/project/randy3k/unittesting/build/1.0.413) and it is still working.

**Comment by randy3k** [comment]
Oh, I can reproduce in another [repo](https://ci.appveyor.com/project/randy3k/unittesting-example/build/job/h7bx8lxqkpqerl6b).

**Comment by randy3k** [comment]
It seems that the cmdlet `start-filedownload ` is broken.

**Comment by niosus** [comment]
Yeah, I also ran it there. Seems like the start-filedownload hangs

**Comment by randy3k** [comment]
I found a solution: just update your `appveyor.yml` as [here](https://github.com/randy3k/UnitTesting-example/blob/0e5759ed3e83e57a349c6b93c9ed357b4b71c43d/appveyor.yml#L10)

**Comment by randy3k** [comment]
It will be fixed by later this week.
http://help.appveyor.com/discussions/problems/5318-start-filedownload-freezes

**Comment by niosus** [comment]
Thanks a lot for the answer! Worked like charm.
