### ISSUE TITLE
Async testing

### ISSUE THREAD

**Issue by rchl** [randy3k/UnitTesting#48]
I'm not sure if it's an issue with this plugin or with Python unittest module itself, but I believe async testing is nor supported? If so, is that something that could be supported?

I suppose some kind of sleeping workaround can be used sometimes but it's quite terrible.

Feel free to close if it's not an issue with the plugin itself.

**Comment by randy3k** [comment]
Do you mean testing async code or running the tests asynchronically?
Have a look at [Deferable Testing](https://github.com/randy3k/UnitTesting-example#deferred-testing) and [Async Testing](https://github.com/randy3k/UnitTesting-example#async-testing-st-3-only)

**Comment by rchl** [comment]
Testing async code.
I'm not sure those two options are really ideal for my use case.

I'm thinking of a case like:

```python
def test_async_code(self):
  def on_processed(results):
    self.assert...

  processor = Processor()
  processor.process(self.on_processed)
```
`processor.process` would do some work on another thread and call `on_processed` when done where we would assert something.

I haven't tried, and I doubt it would, but maybe that would work in async mode? The main thing here is that the body of the test function returns before `on_processed` is called.

**Comment by randy3k** [comment]
Both options fit your use case.


Assumming `processor.process` is non-blocking. With the async testing, you could do something along this line

```python
def test_async_code(self):
  condition = threading.Condition()
  def on_processed(results):
    self.assert...
    condition.acquire()
    condition.notify()
    condition.release()

  processor = Processor()
  processor.process(self.on_processed)
 
  condition.acquire()
  condition.wait(30)
  condition.release()
```

As `test_async_code` is running asynchronically, the `condition.wait` does not block the main thread.

**Comment by randy3k** [comment]
If you use the deferrable testcase (assuming that `processor.process` is non-blocking), you could do something like

```python
def test_async_code(self):
   done = False
  def on_processed(results):
    self.assert...
    done = True

  processor = Processor()
  processor.process(self.on_processed)

  while not done:
    yield 1000
  
```

The `test_async_code` will be executed in the main thread, the while loop will keep the function running until `done` is modified.

**Comment by rchl** [comment]
Thanks for the examples. I might do something like this next time.

I still think that it's not very clean and adds quite a bit of boiler plate. I would imagine just a different type of testcase class that would wait for the testcase to call `self.done()` or similar when it has finished testing. There would of course also be some timeout (configurable) that would fail the testcase if `self.done()` did not get called.

**Comment by randy3k** [comment]
You could always extend `unittest.TestCase` to cover your own use case. Of course, it would be a great idea to ship another test case other than `DeferableTestCase` out of the box.

**Comment by rchl** [comment]
Well, feel free to close this issue if you are not planning on adding such thing.
I think it would be great to have something like AsyncTestCase that would use one of those methods behind the curtain.

**Comment by randy3k** [comment]
I have given it a thought, but testing async code comes with a lot of variations. It would be easier to let a user define their own TestCase.
