### ISSUE TITLE
generate coverage

### ISSUE THREAD

**Issue by niosus** [randy3k/UnitTesting#49]
I am not sure you should be the addressee here, but it would be cool to be able to generate test coverage alongside running the tests.

**Comment by randy3k** [comment]
It is already supported. Please check the docs. I am on a mobile and cannot give you much details.

I recall you that you are using the async option, which does not play well with coverage. You may need to switch to the deferred testing option.

**Comment by niosus** [comment]
oh, sorry then. Missed it somehow.
