### ISSUE TITLE
specify ouput file for coverage

### ISSUE THREAD

**Issue by niosus** [randy3k/UnitTesting#50]
Please tell me if I missed it, but it seems that there is no way to define an output file for the tests. I am using codacy for automated code reviews on my project and they seem to require `coverage.xml` as the output of the tests, while your plugin produces only `.coverage` file if I understand everything correctly. Would it be possible to configure this?

**Comment by randy3k** [comment]
Check this http://stackoverflow.com/questions/4755131/how-to-output-coverage-xml-with-nosetests

**Comment by niosus** [comment]
Indeed. Thanks. That'll do.
