### ISSUE TITLE
cannot run on Bitbucket Pipelines

### ISSUE THREAD

**Issue by guillermooo** [randy3k/UnitTesting#51]
I've modified the scripts for Travis and got as far as executing *RunTests*, but it invariably results in a timeout ("Sublime Text is not responding"). I have no idea why ST is getting stuck. BBPL run Python 2.7. I've also tried running 0 tests and even so the timeout triggers.

<hr>

 BBPL use Docker. I have little experience with Docker myself, but it may possible to create a testing environment as a Docker image and import that from BBPL.

**Comment by randy3k** [comment]
I guess it is because `sh -e /etc/init.d/xvfb start` does not work at bitbucket pipeline? I didn't check : does BBPL documentation mention how to open a GUI?

**Comment by guillermooo** [comment]
Xvfb is present and should be running as expected in the [default BBPL Docker image](https://confluence.atlassian.com/bitbucket/using-docker-images-as-build-environments-792298897.html). Note that ST seems to run ok for initialization (the Data folder is created and populated), but then it gets stuck. I also suspected that was the issue, but I'm not sure it actually is.

**Comment by guillermooo** [comment]
The `/etc/init.d/xvfb` script, however, does not exist. I'm using a custom script for starting xvfb.

**Comment by guillermooo** [comment]
Maybe related to https://github.com/randy3k/UnitTesting/pull/69

(That PR refers to MacOS, however.)
