### ISSUE TITLE
Setup instructions

### ISSUE THREAD

**Issue by jrappen** [randy3k/UnitTesting#52]
Trying to set up UnitTesting for [jrappen/sublime-distractionless](https://github.com/jrappen/sublime-distractionless), but failing.

Is there more reference material other than the `UnitTesting-example`? Or is there a list of points to check when trying to set this up correctly?

**Comment by randy3k** [comment]
To fix travis error, change these [lines][1] to

```yaml
env:
    global:
        - PACKAGE="distractionless"
```

Also, you need to create a new view at [here][2], similar to [3].


[1]: https://github.com/jrappen/sublime-distractionless/blob/2c7d4571452021ffcb4b6bb7d65a172543934b4a/.travis.yml#L2
[2]: https://github.com/jrappen/sublime-distractionless/blob/2c7d4571452021ffcb4b6bb7d65a172543934b4a/tests/test_distractionless.py#L9
[3]: https://github.com/randy3k/UnitTesting-example/blob/c38f32f567b86bb104132fba1117667480895065/tests/test.py#L12-L12

**Comment by jrappen** [comment]
@randy3k Thanks, Travis seems to work now after fixing it in jrappen/sublime-distractionless@2c42e57. I have to fix my test though and maybe feed characters one by one to reach the 10 characters switch.

Do I put the Coveralls token into the Travis CI and AppVeyor settings? I'd appreciate a reference there, too. Thanks!

**Comment by randy3k** [comment]
You just need to switch on coveralls, travis will communicate to coveralls automatically. It is a bit complicated to utilize appveyor, travis and coveralls all three together. My suggestion is to forget about appveyor. 

Note that if you need the UI to respond, it may be necessary to use deferred test case or run the tests asynchronous.
https://github.com/randy3k/UnitTesting-example#deferred-testing
or 
https://github.com/randy3k/UnitTesting-example#async-testing-for-sublime-text-3
