### ISSUE TITLE
Failures on OSX

### ISSUE THREAD

**Issue by gerardroche** [randy3k/UnitTesting#57]
I've been getting failures on OSX. They seem like random failures because they only seemed to appear on some branches even when the checkouts are identical. I think I've narrowed it down to an issue with "close_windows_when_empty" setting, but not sure yet what the best to solve it is or why it's happening.

In build 3126 if `close_windows_when_empty` is true then Sublime Text won't open. It seems like ST is crashing, it's not, it's just opening and then instantly closing due to a bug with that setting.

The `install_sublime_text.sh` script anticipates this:

https://github.com/randy3k/UnitTesting/blob/1f97a12a8dc0a1a920a4e644a5be0769e4c8e010/sbin/install_sublime_text.sh#L90

```
if [ ! -f "$STP/User/Preferences.sublime-settings" ]; then
    echo creating sublime package directory
    mkdir -p "$STP/User"
    # make sure a new window will be opened
    echo '{"close_windows_when_empty": false }' > "$STP/User/Preferences.sublime-settings"
fi
```

However, on some branches on OSX it looks like that settings file isn't being created which causes failures. It looks like it's an issue on older branches which makes me think it's some issue with Travis caching that settings file and the code above won't create the settings if the preferences file already exists.

For example:

On this `master` branch there are failures: [master](https://travis-ci.org/NeoVintageous/NeoVintageous/jobs/258236999)

When I create a new branch off the master branch it runs fine: [upgrades](https://travis-ci.org/NeoVintageous/NeoVintageous/jobs/258286714)

Combing through the log file the master branch is missing the message "creating sublime package directory" which means the above is not being executed and so I'm guessing it's failing because "close_windows_when_empty" isn't being set to false.

This is at least my initial guess. I can't see anything else it could be.

**Comment by randy3k** [comment]
My guess is https://github.com/randy3k/UnitTesting/blob/1f97a12a8dc0a1a920a4e644a5be0769e4c8e010/sbin/install_sublime_text.sh#L53 opens and closes sublime text. If it closes faster enough, the Preference file won't be created and the `close_windows_when_empty` settings will be correctly applied.

We just need to just that last session to the front.

**Comment by randy3k** [comment]
hope 63fb79211556f2cdd44a3d751db874ee6ac7d591 and `0.10.6` will fix it.

**Comment by randy3k** [comment]
Let me know if the latest release fix the random error. It should actually be discovered earlier, however we don't have enough users to allow such.

**Comment by gerardroche** [comment]
How can I go about testing it. There doesn't seem to be an easy way to select to use the latest master branch of UnitTesting. It would be nice to be able rerun failing builds with the latest version UnitTesting. We can set environment variables in Travis e.g. you can set `UNIT_TESTING_MASTER=true` and then rerun the build. If UnitTesting could use an environment variable like this it will make it easier to toggle the latest version on for testing.

**Comment by randy3k** [comment]
I have just tagged a release, it should use the latest version now. To use a different tag, check this https://github.com/randy3k/AutoWrap/blob/master/.travis.yml

I will improve the docs once I have time...

**Comment by gerardroche** [comment]
Yes it's fixed. I reran the failing builds using UnitTesting master and they all pass now. Thanks.

The `UNITTESTING_TAG` environment variable is exactly what I was looking for. With that you can set the tag or branch of UnitTesting to use without needing to modify the build itself. You can add the environment variable in the Travis Ci setting panel. Rerunning a build are setting that will use the latest UnitTesting. Very useful because it saves having to needlessly edit the build itself. 

![screenshot from 2017-07-28 19-49-20](https://user-images.githubusercontent.com/44148/28733016-215164c2-73d2-11e7-9f00-787c08f3d779.png)

**Comment by randy3k** [comment]
Thanks for bringing up this, I didn't realize there is such a usage.
