### ISSUE TITLE
Enhance color scheme testing

### ISSUE THREAD

**Issue by buildersbrewery** [randy3k/UnitTesting#59]
I'd appreciate the `develop` branch of @gerardroche's fork being merged into `master` here.

Compare: <https://github.com/randy3k/UnitTesting/compare/master...gerardroche:develop>

---

> This is for me to keep track of events...

**Comment by randy3k** [comment]
Awesome. I will look into it.

**Comment by gerardroche** [comment]
I intend on sending a PR once the feature the stable, which it pretty much is at this point. I'll send a  PR. I think it can be added as is, it gets the job done.

**Comment by randy3k** [comment]
We also need to extend the appveyor script.

**Comment by gerardroche** [comment]
Appveyor wasn't a priority for me. I also know little to nothing of PowerShell. I'm not sure when I'd get time to add support for appveyor, but I think it's something that can be added later.

**Comment by randy3k** [comment]
Does `color-scheme-unit"` run on Windows? I am happy to modify the appveyor script of Windows is supported.

**Comment by buildersbrewery** [comment]
@randy3k @gerardroche Thanks to both of you.

**Comment by gerardroche** [comment]
Yes it runs on windows. Appveyor support would be great. I'll try send a PR later today.
