### ISSUE TITLE
Question about coverage

### ISSUE THREAD

**Issue by tomv564** [randy3k/UnitTesting#63]
Thanks for making sublime-integrated testing so easy!

I just added a very simple test case to LSP in https://github.com/tomv564/LSP/commit/9e0c86d330be6b89eccedee4ad9c2945642375a8, and got high coverage numbers when I ran "Test Current Package with Coverage":
```
test_conversion (test_protocol.PointTests) ... ok

----------------------------------------------------------------------
Ran 1 test in 0.015s

OK

Name                            Stmts   Miss  Cover
---------------------------------------------------
boot.py                            19      0   100%
plugin/__init__.py                  0      0   100%
plugin/code_actions.py             52     33    37%
plugin/completion.py              161    107    34%
plugin/configuration.py            91     62    32%
plugin/core/__init__.py             0      0   100%
plugin/core/clients.py             74     43    42%
plugin/core/configurations.py      68      9    87%
plugin/core/diagnostics.py         65     44    32%
plugin/core/documents.py          148    100    32%
plugin/core/edit.py                39     27    31%
plugin/core/events.py              19      6    68%
plugin/core/logging.py             14      4    71%
plugin/core/main.py               131     42    68%
plugin/core/panels.py              18     10    44%
plugin/core/protocol.py           187     47    75%
plugin/core/rpc.py                145     75    48%
plugin/core/settings.py           116     12    90%
plugin/core/url.py                  8      1    88%
plugin/core/workspace.py           46     26    43%
plugin/definition.py               35     22    37%
plugin/diagnostics.py             135     88    35%
plugin/formatting.py               37     25    32%
plugin/hover.py                    72     48    33%
plugin/references.py               61     42    31%
plugin/rename.py                   31     20    35%
plugin/signature_help.py          106     73    31%
plugin/symbols.py                  35     21    40%
---------------------------------------------------
TOTAL                            1913    987    48%
```

I would like to configure my package / UnitTesting so only coverage on `plugin/core/protocol.py` is reported ( so I don't get "free" coverage from module initialisation / package reloading) - is this possible?

**Comment by randy3k** [comment]
I believe it is common to cover the initialization step. Otherwise, one can never achieve 100% coverage.

Is there any particular reason you need the coverage without initialization?

**Comment by tomv564** [comment]
I see the 90% coverage on `settings.py` as misleading. Yes, the large majority of the code has "survived" initialisation, but there is not a single test confirming that it is doing the right thing. (See also: https://www.ibm.com/developerworks/java/library/j-cq01316/)

If I wanted to try to exclude initialisation, I could move the reload statement up a bit here? https://github.com/randy3k/UnitTesting/blob/391bd15dcd7d4222dde5e8918a8293bce4cbdd37/unittesting/test_coverage.py#L40-L43

**Comment by randy3k** [comment]
Yes, I agree that it is misleading. But one can argue that surviving the initialization step is also an essential part of the coverage test.

Anyway, if you want to turn if off, you just need to move the`self.reload_package` command before `cov.start()`.

**Comment by randy3k** [comment]
added a new setting `reload_package_on_testing`

https://github.com/randy3k/UnitTesting/blob/d9f600080bcdc179927545f9701b3e81bd2c23bb/unittesting.json

to disable reloading package as all.

**Comment by tomv564** [comment]
Thank you for this setting, it works great!
