### ISSUE TITLE
ColorSchemeUnit runner could not be imported

### ISSUE THREAD

**Issue by evandrocoan** [randy3k/UnitTesting#72]
What is this thing showing up in my console when I start up Sublime Text?

https://github.com/randy3k/UnitTesting/blob/a8c7a6d6cd87f057fbd03c41cec41dba35e6bdf6/unittesting/test_color_scheme.py#L6-L9

**Comment by randy3k** [comment]
Should not be that hard to google: https://packagecontrol.io/packages/ColorSchemeUnit

**Comment by evandrocoan** [comment]
I have googled:

![image](https://user-images.githubusercontent.com/5332158/34233501-f229827a-e5cc-11e7-87b6-2a7df143dfdd.png)

Perhaps it was an unfortunate choice of keywords?

Why the message on the console, when starting up the application, instead of show it when the user attempted to use it?

**Comment by gerardroche** [comment]
@randy3k Perhaps we should omit the message or only import ColorSchemeUnit at runtime and only if the color scheme test command is run?

**Comment by randy3k** [comment]
👍  for importing the module dynamically.
